### PR TITLE
Implement new `srcCreds` in vlt-rcp #181

### PR DESCRIPTION
**Pull request by tripodsan**
please merge after https://issues.apache.org/jira/browse/JCRVLT-174 is fixed and Filevault 3.1.40 is released.

### CODE REVIEW

**Comment by justinedelson** [comment]
@tripodsan If this new version of the RCP bundle is going to be a requirement, I think we will want to alert users with an older version of the bundle that they need to upgrade. Any thoughts on how this can be done?

**Comment by tripodsan** [comment]
the fix in JCRVLT-174 treats the credentials differently so they won't show up in the log anyways. so we actually don't need _this_ changes. _If_ it would implement a more sophisticated REST API, the available actions/parameters would be self described and the client could intelligently choose the desired method.

As a short fix, we could include an API version in the response to http://localhost:4502/system/jackrabbit/filevault/rcp that the client could check.

**Comment by davidjgonzalez** [comment]
Will add a note to the docs page - this is fairly dated now so folks should be update their FV if they havent already.

**Comment by davidjgonzalez** [comment]
@tripodsan is vlt-rcp 3.1.40+ expected to work with AEM 6.3 GA? It's reported that the vlt-rcp 3.1.40 bundle does not start on AEM 6.3 GA (havent checked CFPs or SPs)

```
org.apache.jackrabbit.vault.rcp-3.1.40.jar it failed to start due to a missing dependencies:
org.apache.jackrabbit.spi.commons.tree,version=[2.13.5,3) -- Cannot be resolved
org.apache.jackrabbit.webdav.client.methods,version=[1.1.0,2) -- Cannot be resolved
org.apache.jackrabbit.webdav.header,version=[1.1.0,2) -- Cannot be resolved 
```

**Comment by kwin** [comment]
The issue with AEM 6.3 compatibility should be fixed with the new version (https://issues.apache.org/jira/browse/JCRVLT-436).

**Pull request merged**
