### PR TITLE
Tag Maker

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Tags are hugely power in facilitating the organization of content in AEM. Many implementation have large, complex tagging structures that are originally defined by the business in Excel as it allows for a clean hierarchical modelling while maintaining the flexibility to "feel out" how the taxonomy should work. It is also a tool familiar to most folks on the business side.

Tag Maker allows Tag hierarchies to be defined in Excel, exported as CSV and imported into AEM as tags. A key element (aside for a nice Web UI) is Tag Maker supports pluggable Tag Data Converters (and comes w/ 3 OOTB). 

Tag Data Converters process each "cell" (or CSV field) to derive a Tag Title and Tag Name (node name).

OOTB converters are

* Default: Cell value is the Title, Node name is `JcrUtil.createValidName(<the title>)` (_ for spaces, all lowercase, etc.)
* Lowercase and Dashes: Cell value is the Title, Node name is the title as all lower case, [a-z09-], all non-matching chars are changed to -'s and there can never be more than one - in a row. Also, & is turned to -and- and / is turned to -or-
* Handlebars: Cell is in the format `<Title> {{ <Node name> }}`

Column A is always the Tag Namespace and the subsequent cells are the Tag hierarchy.

Example Excel in Handlebars format (note the Title and Node name are discrete)

screenshot_4_26_15__9_33_am

tag_maker___acs_aem_tools

tag_maker___acs_aem_tools

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
Handlebars Tag Converter is acting strange; Needs fix before PR.

**Comment by justinedelson** [comment]
One thing which confuses me about this - the Handlebars Tag Converter doesn't actually use Handlebars...

**Comment by davidjgonzalez** [comment]
@justinedelson i just called it that since it wraps the node name in {{ }} ... Im open to another less-confusing name.

**Comment by davidjgonzalez** [comment]
@justinedelson come up w/ a better name for the "Handlebars" transfomer? Or can we merge?

**Comment by davidjgonzalez** [comment]
@justinedelson renamed "Handlebars" to "Title {{ node-name }}" 

Also added Fallback converter so you can have 2 types in a single CSV which turns out to be a more usual use-case (Title {{ node-name }} and whatever the fallback is ...

**Comment by davidjgonzalez** [comment]
2015-06-08 at 11 43 am

**Pull request merged**
