### PR TITLE
VLT-RCP Enchancements

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Aligned the visual aesthetic a little more closely to the rest of ACS Tools.

Added a check during init() so this tool auto-detects the version of VLT-RCP (it checks the URIs) and uses the one that returns a 200.

(Note the Play icon is not the Treeexpand + icon in the instruction message; fixed after screenshot was taken)
vlt-rcp___acs_aem_tools

vlt-rcp___acs_aem_tools

Friendly message if VLT is not installed or disabled...

vlt-rcp___acs_aem_tools

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@tyge68 @justinedelson  -- WDYT?

Really dont feel like writing server code to check for the RcpServlet path .. i think this check is sufficient.

**Comment by davidjgonzalez** [comment]
@tyge68  can you confirm that we dont need the ACE JS or Underscore clientlibs dependencies? I didnt see them used anywhere and everything seems fine without them.

**Comment by tyge68** [comment]
Hi David,

That's possible I just re-use same logic as in other of the similar pages
from other tools, so it can be that some javascript libraries are not
really necessary.

Feel free to adjust if that is needed.

Best regards,
-Thierry

2015-04-26 18:44 GMT+02:00 david g. <notifications@github.com>:

**Comment by justinedelson** [comment]
LGTM, but maybe add a third bullet which says something about how the URL must be accessible, i.e. If you are using the dispatcher or another reverse proxy. Or is this obvious?

**Comment by davidjgonzalez** [comment]
Easy enough to add, don't see why we shouldn't!

**Comment by davidjgonzalez** [comment]
Added the messaging

**Comment by davidjgonzalez** [comment]
@justinedelson @tyge68  we good to merge?

**Comment by tyge68** [comment]
It looks great , nice job David :)
Cheers,
-Thierry

2015-06-05 14:51 GMT+02:00 david g. <notifications@github.com>:

**Comment by davidjgonzalez** [comment]
@tyge68 i just applied some lipstick; thanks for building this out - all the credit goes to you!

im excited to get to use this in the future!

**Pull request merged**
