### PR TITLE
So that acs commons bundle doesn't get installed and doesn't conflict…

### PR DESCRIPTION
**Pull request by mehtarachna**
… with other versions of acs commons.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
Using #164 instead .. thanks for noticing and submitting the PR. Sorry we missed the intent of this.

**Comment by mehtarachna** [comment]
I think this is different, we don't want to install acs aem commons bundle via acs tools as we have forked acs aem commons of specific version and if it gets installed via acs tools, there will be conflict, please check the commit, it will not install acs commons if it's already there.  Please reopen and review, if possible merge it so that we don't need to fork acs tools as well for this change.  Please let me know if you have any questions.  Many thanks.

**Comment by justinedelson** [comment]
ACS AEM Commons should *never* get installed as part of ACS AEM Tools.

**Comment by mehtarachna** [comment]
Thanks Justin for the reply, that was the only reason we had to fork acs tools and make acs aem commons optional so that it doesn't install acs aem commons.  I am hoping once 164 is merged in, We don't need to fork acs tools and we can use that version instead.

**Pull request closed without merging**
