### PR TITLE
adding support to QueryBuilder map syntax to Explain Query

### PR DESCRIPTION
**Pull request by justinedelson**
@davidjgonzalez @chetanmeh please review

### CODE REVIEW

**Comment by chetanmeh** [comment]
Thanks @justinedelson! This serves the purpose quite a bit. 

However what I was thinking was like this. In many situations I have seen that user is just dealing with QB. The utility of Explain Tool (apart from Explain) is getting precise logs for that specific thread. Note that given how guessTotal is used QB might execute same query multiple times.

Currently I have to leave all that support and instead do
1. Turn on logs for Oak and CQ QB , 
2. execute the QB page and
3. Then turn off the log
4. grep the logs belonging to the thread from QB
5. See which is from your query. At time customer system is being used by other people also

To simplify that flow what I was thinking about was to add support for QB within Explain. So instead a person would use following flow
1. Go to Explain tool
2. Add the QB query
3. Execute. ExplainTool would also collect logs from QB category and also from Oak
4. Get the dump of logs and analyze that

This would require some change in way we collect logs today as QB would not perform explain. I would think about it further and see if it can be implemented.

Best would be to get QB also collect Oak logs but there I am constrained by release process. Hence trying in Explain tool side

**Comment by davidjgonzalez** [comment]
@justinedelson LGTM 

@chetanmeh WRT to  "3. Execute. ExplainTool would also collect logs from QB category and also from Oak", you're looking for the time to filter right? Is there anything else you look for?

We mentioned getting total results, but that would be applicable to any query language type.

**Comment by justinedelson** [comment]
Is getting the logs from the QB as simple as adding more categories to the configuration? Right now, there are just two Oak-related logger categories?

**Comment by davidjgonzalez** [comment]
Check out decide(..) in the servlet

Adding new loggers  will work in oak version under 1.0.9, however if mdc is enabled, then the qb results would be filtered out since they aren't tagged w for explain query.

**Comment by davidjgonzalez** [comment]
@justinedelson just PR'd to your fork w Querybuilder logging support.

**Comment by davidjgonzalez** [comment]
Here's the JSON export of a QueryBuilder query on Oak 1.0.9 ..

```
{
    "statement": "type=cq:Page\nproperty=jcr:content/cq:template\nproperty.value=/apps/geometrixx/templates/homepage",
    "language": "queryBuilder",
    "explain": {
        "logs": [
            "executing query (URL):\nproperty=jcr%3acontent%2fcq%3atemplate&property.value=%2fapps%2fgeometrixx%2ftemplates%2fhomepage&type=cq%3aPage\n",
            "executing query (predicate tree):\nROOT=group: [\n    {property=property: property=jcr:content/cq:template, value=/apps/geometrixx/templates/homepage}\n    {type=type: type=cq:Page}\n]\n",
            "xpath query: //element(*, cq:Page)[jcr:content/@cq:template = '/apps/geometrixx/templates/homepage']\n",
            "xpath query creation took 12 ms\n",
            ">> xpath query returned 7 results (getSize)\n",
            "entire query execution took 17 ms\n",
            "cost using filter Filter(query=explain select [jcr:path], [jcr:score], * from [cq:Page] as a where [jcr:content/cq:template] = '/apps/geometrixx/templates/homepage' /* xpath: //element(*, cq:Page)[jcr:content/@cq:template = '/apps/geometrixx/templates/homepage'] */, path=*, property=[jcr:content/cq:template=/apps/geometrixx/templates/homepage])\n",
            "cost for aggregate lucene is Infinity\n",
            "Evaluating plan with index definition IndexDefinition : /oak:index/lucene\n",
            "Index is old format. Not supported\n",
            "cost for lucene-property is Infinity\n",
            "cost for reference is Infinity\n",
            "getPlans(Filter, List<OrderEntry>, NodeState)\n",
            "getPlans() - filter: Filter(query=explain select [jcr:path], [jcr:score], * from [cq:Page] as a where [jcr:content/cq:template] = '/apps/geometrixx/templates/homepage' /* xpath: //element(*, cq:Page)[jcr:content/@cq:template = '/apps/geometrixx/templates/homepage'] */, path=*, property=[jcr:content/cq:template=/apps/geometrixx/templates/homepage]) - \n",
            "getPlans() - sortOrder: null - \n",
            "getPlans() - rootState: { jcr:primaryType = rep:root, jcr:mixinTypes = [rep:RepoAccessControllable, rep:AccessControllable], sling:target = /index.html, sling:resourceType = sling:redirect, :async : { async-temp = [5e57d981-b432-49ae-8409-ff1f284c6dcc, cbfe35b9-9478-41c1-97c5-adf16d54c95a], async = cbfe35b9-9478-41c1-97c5-adf16d54c95a, async-LastIndexedTo = 2015-04-30T23:38:02.464-04:00 }, tmp = { ... }, home = { ... }, dingo : { jcr:primaryType = cq:Tag, jcr:createdBy = admin, jcr:title = Dingo, jcr:created = 2015-04-25T11:34:42.602-04:00, :childOrder = [], jcr:description = en, sling:resourceType = cq/tagging/components/tag }, oak:index = { ... }, cat : { jcr:primaryType = cq:Tag, jcr:createdBy = admin, jcr:title = Cat, jcr:created = 2015-04-25T11:34:42.581-04:00, :childOrder = [], jcr:description = en, sling:resourceType = cq/tagging/components/tag }, jcr:system = { ... }, lion : { jcr:primaryType = cq:Tag, jcr:createdBy = admin, jcr:title = Lion, jcr:created = 2015-04-25T11:34:42.598-04:00, :childOrder = [], jcr:description = en, sling:resourceType = cq/tagging/components/tag }, etc = { ... }, system = { ... }, content = { ... }, bin : { jcr:primaryType = nt:folder, jcr:mixinTypes = [mix:versionable], jcr:createdBy = admin, jcr:versionHistory = 182a9098-45d9-48ef-92f7-2c58559d950f, jcr:predecessors = [], jcr:created = 2015-04-05T14:50:16.658-04:00, jcr:baseVersion = 63faf12e-fad1-4abf-97c8-78ef630045df, jcr:isCheckedOut = false, jcr:uuid = 40ed38c9-cb13-41dc-8602-0249e2c1b4c2 }, rep:policy = { ... }, libs = { ... }, rep:repoPolicy = { ... }, var = { ... }, apps = { ... }, dog : { jcr:primaryType = cq:Tag, jcr:createdBy = admin, jcr:title = Dog, jcr:created = 2015-04-25T11:34:42.592-04:00, :childOrder = [], jcr:description = en, sling:resourceType = cq/tagging/components/tag } } - \n",
            "cost for ordered is Infinity\n",
            "cost for nodeType is 10005.0\n",
            "property cost for cq:template is 9.0\n",
            "Cheapest property cost is 9.0 for property jcr:content/cq:template\n",
            "cost for property is 9.0\n",
            "cost for traverse is 1.0E8\n"
        ],
        "plan": "[cq:Page] as [a] /* property cq:template=/apps/geometrixx/templates/homepage where [a].[jcr:content/cq:template] = cast('/apps/geometrixx/templates/homepage' as string) */",
        "propertyIndexes": [
            "cq:template"
        ]
    }
}
```

**Comment by chetanmeh** [comment]
Thanks @davidjgonzalez ! That was what I was looking for. It would greatly reduce the noise in collecting required details and allows a nice summary for the problem being faced

**Comment by davidjgonzalez** [comment]
@justinedelson FYI - had a offline convo w @chetanmeh  and in my PR to you, we should (eventually) prevent that startsWith(..) check everywhere.

```
in the servlet before performing the query set a threadlocal flag indicating explain in action! and in turbo filter do not mess until that threadlocal is found to be true
```

(Just capturing this since its bedtime for me)

**Comment by davidjgonzalez** [comment]
@justinedelson - FYI - you have a PR to your fork w a bunch of enhancements that were build on top of your QB support code. The PR takes care of:

1) Getting the result count and timing
2) Getting the QB logs
3) Download result as a JSON blob 
4) Adds a ThreadLocal flag to make the decide(..) check always fast(er)

**Pull request closed without merging**
